### PR TITLE
fixed binary protocol changes

### PR DESCRIPTION
**Pull request by AuthenticEshkinKot**
Fix for issue #149

### CODE REVIEW

**Review by aensidhe — CHANGES_REQUESTED** [review]
Changing constants will break backwards compatibility.

Could you provide a documentation for that change?

**Comment by AuthenticEshkinKot** [comment]
https://www.tarantool.io/ru/doc/latest/dev_guide/internals/box_protocol/
IPROTO_FIELD_NAME=0x00
IPROTO_SQL_INF O=0x42
SQL_INFO_ROW_COUNT (0x00)

**Comment by AuthenticEshkinKot** [comment]
I've added support of old enum values

**Comment by Totktonada** [comment]
I would not bother much about tarantool 2.0 support: it was development tarantool series and had no real releases. However, if it is cheap, I don't mind.

**Review by aensidhe — APPROVED** [review]

**Comment by aensidhe** [comment]
Why do we need Task.Run change?

**Comment by AuthenticEshkinKot** [comment]
Honestly, I don't know. It was in @ilnardinio 's commit.

**Comment by ilnardinio** [comment]
Sometimes there was deadlock in .Net Core (I do not remember the exact version). Task.Run was workaround.

**Pull request merged**
